CREATE DATABASE IF NOT EXISTS online_banking_db;
USE online_banking_db;
CREATE TABLE users ( id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(100) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, contact VARCHAR(15) NOT NULL, address VARCHAR(255) NOT NULL, role ENUM('ADMIN','BANK_MANAGER','CUSTOMER') NOT NULL, status ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE', created_date DATETIME DEFAULT CURRENT_TIMESTAMP );
